### ISSUE TITLE
help system (help everywhere)

### ISSUE THREAD

**Issue by tballmsft** [microsoft/pxt-tileworld#34]

**Comment by charllespalani** [comment]
Application wrapping in progress. App Wrapping Tool Version: 1.0.2676.4
Failed to package app.
        com.microsoft.intune.mam.apppackager.utils.AppPackagerException: Failed to decode the apk file.
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decodeAPK(APKToolWrapper.java:142)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:79)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
        brut.androlib.AndrolibException: brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
                brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:307)
                brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decodeAPK(APKToolWrapper.java:140)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:79)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
        brut.directory.DirectoryException: java.util.zip.ZipException: zip file is empty
                brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:55)
                brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
                brut.directory.ExtFile.getDirectory(ExtFile.java:52)
                brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
                brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decodeAPK(APKToolWrapper.java:140)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:79)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
        java.util.zip.ZipException: zip file is empty
                java.util.zip.ZipFile.open(Native Method)
                java.util.zip.ZipFile.<init>(Unknown Source)
                java.util.zip.ZipFile.<init>(Unknown Source)
                java.util.zip.ZipFile.<init>(Unknown Source)
                brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:53)
                brut.directory.ZipRODirectory.<init>(ZipRODirectory.java:38)
                brut.directory.ExtFile.getDirectory(ExtFile.java:52)
                brut.androlib.ApkDecoder.hasResources(ApkDecoder.java:305)
                brut.androlib.ApkDecoder.decode(ApkDecoder.java:103)
                com.microsoft.intune.mam.apppackager.utils.APKToolWrapper.decodeAPK(APKToolWrapper.java:140)
                com.microsoft.intune.mam.apppackager.AppPackager.packageApp(AppPackager.java:79)
                com.microsoft.intune.mam.apppackager.PackagerMain.mainInternal(PackagerMain.java:223)
                com.microsoft.intune.mam.apppackager.PackagerMain.main(PackagerMain.java:59)
Failed to decode the apk file.

im getting this error when i do app wrapping for intune
